backend:
  name: github
  repo: realinternetman/realinternetman.com
  branch: main

media_folder: content/assets
public_folder: assets
publish_mode: editorial_workflow
show_preview_links: true

collections:
  - name: posts
    label: Posts
    folder: content/posts
    create: true
    slug: &posts_slug '{{year}}-{{month}}-{{day}}_{{fields.slug}}'
    summary: '{{year}}-{{month}}-{{day}} - {{title}}'
    fields: &posts_fields
      - { name: title, label: Title }
      - { name: date, label: Date, widget: datetime, required: true }
      - name: tags
        label: 'Tags'
        widget: 'relation'
        collection: 'tags'
        multiple: true
        searchFields: ['label', 'value']
        valueField: 'value'
        displayFields: ['label']
      - { name: body, label: Body, widget: markdown }
      - {
          name: heading_image,
          label: Heading Image,
          widget: image,
          allow_multiple: false,
          required: false,
        }
      - { name: slug, label: Slug, widget: string, required: false }
  - name: tags
    label: Posts > Tags
    folder: content/tags
    create: true
    identifier_field: value
    slug: '{{value}}'
    summary: '[{{category}}] {{label}}'
    fields:
      - { name: label, label: Label }
      - { name: value, label: Value }
      - name: category
        label: Category
        widget: select
        options:
          - { label: Blog, value: blog }
          - { label: Tech, value: tech }

  - name: pages
    label: Pages
    folder: content/pages
    create: true
    identifier_field: title
    slug: '{{fields.slug}}'
    fields:
      - { name: title, label: Title }
      - { name: date, label: Date, widget: datetime }
      - { name: body, label: Body, widget: markdown }
      - { name: slug, label: Slug, widget: string }
